services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=basket_db
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    mem_limit: 1g

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - database
      - external-api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/basket_db
    mem_limit: 512m

  external-api:
    image: nachoferra/external-api-aseca-app:latest
    mem_limit: 256m


volumes:
  database:
    driver: local
