services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=basket_db
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/basket_db

volumes:
  database:
    driver: local
